#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("s_axi_AXILiteS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_AWADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("read_mover_V_V_TDATA", 72, hls_out, 0, "axis", "out_data", 1),
	Port_Property("read_mover_V_V_TVALID", 1, hls_out, 0, "axis", "out_vld", 1),
	Port_Property("read_mover_V_V_TREADY", 1, hls_in, 0, "axis", "out_acc", 1),
	Port_Property("write_mover_V_V_TDATA", 72, hls_out, 1, "axis", "out_data", 1),
	Port_Property("write_mover_V_V_TVALID", 1, hls_out, 1, "axis", "out_vld", 1),
	Port_Property("write_mover_V_V_TREADY", 1, hls_in, 1, "axis", "out_acc", 1),
	Port_Property("in_stream_V_V_TDATA", 128, hls_in, 2, "axis", "in_data", 1),
	Port_Property("in_stream_V_V_TVALID", 1, hls_in, 2, "axis", "in_vld", 1),
	Port_Property("in_stream_V_V_TREADY", 1, hls_out, 2, "axis", "in_acc", 1),
	Port_Property("out_stream_V_V_TDATA", 128, hls_out, 3, "axis", "out_data", 1),
	Port_Property("out_stream_V_V_TVALID", 1, hls_out, 3, "axis", "out_vld", 1),
	Port_Property("out_stream_V_V_TREADY", 1, hls_in, 3, "axis", "out_acc", 1),
	Port_Property("read_mover_halt", 1, hls_out, 7, "ap_none", "out_data", 1),
	Port_Property("read_mover_halt_complete", 1, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("write_mover_halt", 1, hls_out, 9, "ap_none", "out_data", 1),
	Port_Property("write_mover_halt_complete", 1, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "test_direct_dma";
