// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern bool test_direct_dma ( hls::stream< unsigned int > * in_stream,  hls::stream< unsigned int > * out_stream, volatile unsigned int* m_mm2s_ctl, volatile unsigned int* m_s2mm_ctl, volatile unsigned int sourceAddress, volatile unsigned int destinationAddress);

