// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "hls_stream.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;




   #define AUTOTB_TVOUT_out_stream_V  "../tv/cdatafile/c.test_direct_dma.autotvout_out_stream_V.dat"
   #define AUTOTB_TVIN_out_stream_V  "../tv/cdatafile/c.test_direct_dma.autotvin_out_stream_V.dat"
   #define AUTOTB_TVIN_m_s2mm_ctl  "../tv/cdatafile/c.test_direct_dma.autotvin_m_s2mm_ctl.dat"
   #define AUTOTB_TVOUT_m_s2mm_ctl  "../tv/cdatafile/c.test_direct_dma.autotvout_m_s2mm_ctl.dat"
   #define AUTOTB_TVIN_sourceAddress  "../tv/cdatafile/c.test_direct_dma.autotvin_sourceAddress.dat"
   #define AUTOTB_TVIN_destinationAddress  "../tv/cdatafile/c.test_direct_dma.autotvin_destinationAddress.dat"
   #define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.test_direct_dma.autotvout_ap_return.dat"
   #define INTER_TCL  "../tv/cdatafile/ref.tcl"

   #define AUTOTB_TVOUT_PC_out_stream_V  "../tv/rtldatafile/rtl.test_direct_dma.autotvout_out_stream_V.dat"
   #define AUTOTB_TVOUT_PC_m_s2mm_ctl  "../tv/rtldatafile/rtl.test_direct_dma.autotvout_m_s2mm_ctl.dat"
   #define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.test_direct_dma.autotvout_ap_return.dat"

class INTER_TCL_FILE {
    public:
//functions
        INTER_TCL_FILE(const char* name) {
            mName = name;
            out_stream_V_depth = 0;
            m_s2mm_ctl_depth = 0;
            sourceAddress_depth = 0;
            destinationAddress_depth = 0;
            ap_return_depth = 0;
            trans_num =0;
        }
        ~INTER_TCL_FILE() {
            mFile.open(mName);
            if (!mFile.good() ) {
                cout<<"Failed to open file ref.tcl."<<endl;
                exit (1);
            }
            string total_list = get_depth_list();
            mFile<<"set depth_list {\n";
            mFile<<total_list; 
            mFile<<"}\n";
            mFile<<"set trans_num "<<trans_num<<endl;
            mFile.close();
        }
        string get_depth_list () {
            stringstream total_list;
            total_list<<"   {out_stream_V "<< out_stream_V_depth << "}\n";
            total_list<<"   {m_s2mm_ctl "<< m_s2mm_ctl_depth << "}\n";
            total_list<<"   {sourceAddress "<< sourceAddress_depth << "}\n";
            total_list<<"   {destinationAddress "<< destinationAddress_depth << "}\n";
            total_list<<"   {ap_return "<< ap_return_depth << "}\n";
            return total_list.str();
        }
        void set_num (int num , int* class_num) {
            (*class_num) = (*class_num) > num ? (*class_num) : num;
        }
    public:
//variables
        int out_stream_V_depth;
        int m_s2mm_ctl_depth;
        int sourceAddress_depth;
        int destinationAddress_depth;
        int ap_return_depth;
        int trans_num;
    private:
        ofstream mFile;
        const char* mName;
};

#define test_direct_dma AESL_ORIG_DUT_test_direct_dma
extern bool test_direct_dma ( hls::stream< unsigned int > * in_stream,  hls::stream< unsigned int > * out_stream, volatile unsigned int* m_mm2s_ctl, volatile unsigned int* m_s2mm_ctl, volatile unsigned int sourceAddress, volatile unsigned int destinationAddress);
#undef test_direct_dma
bool test_direct_dma ( hls::stream< unsigned int > * in_stream,  hls::stream< unsigned int > * out_stream, volatile unsigned int* m_mm2s_ctl, volatile unsigned int* m_s2mm_ctl, volatile unsigned int sourceAddress, volatile unsigned int destinationAddress) {

    fstream wrapc_switch_file_token;

    wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");

    int AESL_i;

    if (wrapc_switch_file_token.good()) {

        static unsigned AESL_transaction_pc;

        string AESL_token;

        string AESL_num;

        static AESL_FILE_HANDLER aesl_fh;

        bool AESL_return;

        int aesl_tmp_1;

        int aesl_tmp_2 = 0;

        std::vector<unsigned int > aesl_tmp_0;

        int aesl_tmp_4;

        int aesl_tmp_5 = 0;

        aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_token); //[[transaction]]

        aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_token); //pop_size

            aesl_tmp_4 = atoi(AESL_token.c_str());

            aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_stream_V, AESL_token); //[[/transaction]]

        }

        std::vector<unsigned int > aesl_tmp_3;

        aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_token); //data

            sc_bv<32> *out_stream_V_pc_buffer = new sc_bv<32>[1];

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'out_stream_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'out_stream_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    out_stream_V_pc_buffer[i] = AESL_token.c_str();

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_out_stream_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_stream_V)) {

                   exit(1);

                }

            }

            if (i > 0) {

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

                    *(out_stream) = (sc_bv<32>(out_stream_V_pc_buffer[0 + AESL_i].range(31, 0))).to_uint64();

                    AESL_i++;

                }

                }

            delete [] out_stream_V_pc_buffer;

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_m_s2mm_ctl, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_m_s2mm_ctl, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_m_s2mm_ctl, AESL_token); //data

            sc_bv<32> *m_s2mm_ctl_pc_buffer = new sc_bv<32>[1];

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'm_s2mm_ctl', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'm_s2mm_ctl', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    m_s2mm_ctl_pc_buffer[i] = AESL_token.c_str();

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_m_s2mm_ctl, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_m_s2mm_ctl)) {

                   exit(1);

                }

            }

            if (i > 0) {

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

                    *(m_s2mm_ctl) = (sc_bv<32>(m_s2mm_ctl_pc_buffer[0 + AESL_i].range(31, 0))).to_uint64();

                    AESL_i++;

                }

                }

            delete [] m_s2mm_ctl_pc_buffer;

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); //data

            sc_bv<1> ap_return_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    ap_return_pc_buffer = AESL_token.c_str();

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return)) {

                   exit(1);

                }

            }

            if (i > 0) {

                AESL_i = 0; //subscript for rtl array

                AESL_return = (sc_bv<1>(ap_return_pc_buffer.range(0, 0))).to_uint64();

                AESL_i++;

                }

        }

        for (int i = 0; i < aesl_tmp_4; i++) {

            (* out_stream).write(aesl_tmp_3[i]);

        }

        AESL_transaction_pc ++ ;

        return AESL_return;

    } else {

        static unsigned AESL_transaction;

        static AESL_FILE_HANDLER aesl_fh;

        char* tvout_out_stream_V = new char[50];

        char* tvin_out_stream_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_out_stream_V);

        char* tvin_m_s2mm_ctl = new char[50];

        char* tvout_m_s2mm_ctl = new char[50];

        char* tvin_sourceAddress = new char[50];

        char* tvin_destinationAddress = new char[50];

        char* tvout_ap_return = new char[50];

        static INTER_TCL_FILE tcl_file(INTER_TCL);


        int leading_zero;

        std::vector<unsigned int > aesl_tmp_0;

        int aesl_tmp_1 = 0;

        while (!(* in_stream).empty()) {

            aesl_tmp_0.push_back((* in_stream).read());

            aesl_tmp_1 ++;

        }

        std::vector<unsigned int > aesl_tmp_3;

        int aesl_tmp_4 = 0;

        while (!(* out_stream).empty()) {

            aesl_tmp_3.push_back((* out_stream).read());

            aesl_tmp_4 ++;

        }

        sprintf(tvin_out_stream_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_out_stream_V, tvin_out_stream_V);

        sc_bv<32> *out_stream_V_tvin_wrapc_buffer = new sc_bv<32>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

            out_stream_V_tvin_wrapc_buffer[0 + AESL_i].range(31, 0) = *(out_stream);

            AESL_i++;

        }

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvin_out_stream_V, "%s\n", (out_stream_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_out_stream_V, tvin_out_stream_V);

        }

        tcl_file.set_num(1,&tcl_file.out_stream_V_depth);

        sprintf(tvin_out_stream_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_out_stream_V, tvin_out_stream_V);

        delete [] out_stream_V_tvin_wrapc_buffer;

        sprintf(tvin_m_s2mm_ctl, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_m_s2mm_ctl, tvin_m_s2mm_ctl);

        sc_bv<32> *m_s2mm_ctl_tvin_wrapc_buffer = new sc_bv<32>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

            m_s2mm_ctl_tvin_wrapc_buffer[0 + AESL_i].range(31, 0) = *(m_s2mm_ctl);

            AESL_i++;

        }

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvin_m_s2mm_ctl, "%s\n", (m_s2mm_ctl_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_m_s2mm_ctl, tvin_m_s2mm_ctl);

        }

        tcl_file.set_num(1,&tcl_file.m_s2mm_ctl_depth);

        sprintf(tvin_m_s2mm_ctl, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_m_s2mm_ctl, tvin_m_s2mm_ctl);

        delete [] m_s2mm_ctl_tvin_wrapc_buffer;

        sprintf(tvin_sourceAddress, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_sourceAddress, tvin_sourceAddress);

        sc_bv<32> sourceAddress_tvin_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        sourceAddress_tvin_wrapc_buffer.range(31, 0) = sourceAddress;

        AESL_i++;

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvin_sourceAddress, "%s\n", (sourceAddress_tvin_wrapc_buffer).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_sourceAddress, tvin_sourceAddress);

        }

        tcl_file.set_num(1,&tcl_file.sourceAddress_depth);

        sprintf(tvin_sourceAddress, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_sourceAddress, tvin_sourceAddress);

        sprintf(tvin_destinationAddress, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_destinationAddress, tvin_destinationAddress);

        sc_bv<32> destinationAddress_tvin_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        destinationAddress_tvin_wrapc_buffer.range(31, 0) = destinationAddress;

        AESL_i++;

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvin_destinationAddress, "%s\n", (destinationAddress_tvin_wrapc_buffer).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_destinationAddress, tvin_destinationAddress);

        }

        tcl_file.set_num(1,&tcl_file.destinationAddress_depth);

        sprintf(tvin_destinationAddress, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_destinationAddress, tvin_destinationAddress);

        bool AESL_return = AESL_ORIG_DUT_test_direct_dma(in_stream,out_stream,m_mm2s_ctl,m_s2mm_ctl,sourceAddress,destinationAddress);

        int aesl_tmp_2 = (* in_stream).size();

        int aesl_tmp_5 = aesl_tmp_4;

        while (!(* out_stream).empty()) {

            aesl_tmp_3.push_back((* out_stream).read());

            aesl_tmp_4 ++;

        }

        sprintf(tvout_out_stream_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_out_stream_V, tvout_out_stream_V);

        sc_bv<32> *out_stream_V_tvout_wrapc_buffer = new sc_bv<32>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

            out_stream_V_tvout_wrapc_buffer[0 + AESL_i].range(31, 0) = *(out_stream);

            AESL_i++;

        }

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvout_out_stream_V, "%s\n", (out_stream_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_out_stream_V, tvout_out_stream_V);

        }

        tcl_file.set_num(1,&tcl_file.out_stream_V_depth);

        sprintf(tvout_out_stream_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_out_stream_V, tvout_out_stream_V);

        delete [] out_stream_V_tvout_wrapc_buffer;

        sprintf(tvout_m_s2mm_ctl, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_m_s2mm_ctl, tvout_m_s2mm_ctl);

        sc_bv<32> *m_s2mm_ctl_tvout_wrapc_buffer = new sc_bv<32>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

            m_s2mm_ctl_tvout_wrapc_buffer[0 + AESL_i].range(31, 0) = *(m_s2mm_ctl);

            AESL_i++;

        }

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvout_m_s2mm_ctl, "%s\n", (m_s2mm_ctl_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_m_s2mm_ctl, tvout_m_s2mm_ctl);

        }

        tcl_file.set_num(1,&tcl_file.m_s2mm_ctl_depth);

        sprintf(tvout_m_s2mm_ctl, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_m_s2mm_ctl, tvout_m_s2mm_ctl);

        delete [] m_s2mm_ctl_tvout_wrapc_buffer;

        sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

        sc_bv<1> ap_return_tvout_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        ap_return_tvout_wrapc_buffer.range(0, 0) = AESL_return;

        AESL_i++;

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

        }

        tcl_file.set_num(1,&tcl_file.ap_return_depth);

        sprintf(tvout_ap_return, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

        for (int i = 0; i < aesl_tmp_4; i++) {

            (* out_stream).write(aesl_tmp_3[i]);

        }

        delete [] tvout_out_stream_V;

        delete [] tvin_out_stream_V;

        delete [] tvin_m_s2mm_ctl;

        delete [] tvout_m_s2mm_ctl;

        delete [] tvin_sourceAddress;

        delete [] tvin_destinationAddress;

        delete [] tvout_ap_return;

        AESL_transaction++;

        tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

        return AESL_return;

    }
}


